#pragma once
#include <windows.h>

#define FOREGROUND_NORMAL FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE
#define FOREGROUND_LIGHT_GREEN FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define FOREGROUND_LIGHT_RED FOREGROUND_RED|FOREGROUND_INTENSITY

void SetConsoleColor(const WORD color);
void PrintColoredText(const WORD color, const char* text);